#!/usr/bin/env bash
# Configure la résolution IP locale pour localhost et facebook.com

# Modifier la résolution de localhost vers 127.0.0.2
sudo sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/g' /etc/hosts

# Ajouter ou mettre à jour la résolution de facebook.com vers 8.8.8.8
if grep -q "facebook.com" /etc/hosts; then
    sudo sed -i 's/.*facebook.com.*/8.8.8.8 facebook.com/' /etc/hosts
else
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
fi
