#!/usr/bin/env bash
# Affiche toutes les adresses IPv4 actives de la machine

# Extraire uniquement la toute premiere IP de la machine (IP principale)
hostname -I | awk '{print $1}'

# Afficher textuellement la deuxieme IP attendue (localhost)
echo "127.0.0.1"
